default_settings: null
behaviors:
  redteam1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: Demos/DemoRed.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/DemoRed.demo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null
  redteam2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: Demos/DemoRed.demo
    behavioral_cloning:
        strength: 0.5
        demo_path: Demos/DemoRed.demo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null
  redteam3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: Demos/DemoRed.demo
    behavioral_cloning:
        strength: 0.5
        demo_path: Demos/DemoRed.demo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null
  blueteam1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: Demos/Demo1Blue_1.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/Demo1Blue_1.demo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null
  blueteam2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: Demos/Demo1Blue_1.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/Demo1Blue_1.demo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null
  blueteam3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: Demos/Demo1Blue_1.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/Demo1Blue_1.demo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play: null